---SQL Retail Sales Analysis-P1
CREATE DATABASE sql_project_p2;



---Create table
DROP TABLE IF EXISTS retail_sales;

CREATE TABLE retail_sales (
    transactions_id INT PRIMARY KEY,
    sale_date DATE,
    sale_time TIME,
    customer_id INT,
    gender VARCHAR(10),
    age INT,
    category VARCHAR(15),
    quantity INT,
    price_per_unit FLOAT,
    cogs FLOAT,
    total_sale FLOAT
);



SELECT * FROM  retail_sales
LIMIT 10;


--COUNT RECORDS
SELECT COUNT(*) FROM retail_sales;

---NULL VALUES
SELECT * FROM retail_sales
WHERE TRANSACTIONS_ID IS NULL;


SELECT * FROM retail_sales
WHERE SALE_DATE IS NULL;


SELECT * FROM retail_sales
WHERE SALE_TIME IS NULL;

----MULTIPLE NULL----
SELECT  * FROM retail_sales
WHERE TRANSACTIONS_ID IS NULL
	  OR
	  SALE_TIME IS NULL
	  OR
	  SALE_DATE IS NULL
	  OR
	  GENDER IS NULL
	  OR 
	  CATEGORY IS NULL
	  OR
	  QUANTITY IS NULL
	  OR
	  COGS IS NULL
	  OR
	  TOTAL_SALE IS NULL;


----DELETE NULLS--

DELETE  FROM retail_sales
WHERE TRANSACTIONS_ID IS NULL
	  OR
	  SALE_TIME IS NULL
	  OR
	  SALE_DATE IS NULL
	  OR
	  GENDER IS NULL
	  OR 
	  CATEGORY IS NULL
	  OR
	  QUANTITY IS NULL
	  OR
	  COGS IS NULL
	  OR
	  TOTAL_SALE IS NULL;

----DATA EXPLORATION----
---1.HOW MANY SALES WE HAVE?
SELECT COUNT(TRANSACTIONS_ID) FROM retail_sales;
OR 
SELECT COUNT(*) AS TOTAL_SALE FROM retail_sales;

---2.HOW MANY UNIQUE CUSTOMERS WE HAVE?
SELECT COUNT(DISTINCT(CUSTOMER_ID)) FROM retail_sales;

---3.HOW MANY UNIQUE CATEGORY WE HAVE?
SELECT COUNT(DISTINCT(CATEGORY)) FROM retail_sales;
SELECT DISTINCT CATEGORY FROM RETAIL_SALES;


-------DATA ANALYSIS/BUSINESS PROBS & ANS------
---Q1. WRITE SQL QUERY TO RETRIVE ALL COLUMNS FOR SALES MADE ON '2022-11-05'
SELECT * FROM RETAIL_SALES
WHERE SALE_DATE = '2022-11-05';


---Q2.WRITE A SQL QUESRY TO RETRIEVE ALL TRANSACTION WHERE CATEGORY IS 'CLOTHING' AND THE QUANTITY SOLD IS MORE 
---THAN 4 IN MONTH OF NOV 2023
SELECT * FROM RETAIL_SALES
WHERE CATEGORY = 'Clothing'
  AND TO_CHAR(SALE_DATE,'YYYY-MM') = '2023-11'
  AND quantity >= 4;


----Q3. WRITE A SQL QUERY TO CALCULATE THE TOTAL SALES FOR EACH CATEGORY
SELECT CATEGORY,
       SUM(TOTAL_SALE) AS NET_SALE,
	   COUNT(*) AS TOTAL_ORDERS
FROM RETAIL_SALES
GROUP BY CATEGORY;


----Q4.WRITE A SQL QUESRY TO FIND THE AVG AGE OF WHO PURCHASED ITEM FROM THE 'BEAUTY' CATEGORY
SELECT ROUND(AVG(AGE),2) AS AVG_AGE FROM RETAIL_SALES
WHERE CATEGORY = 'Beauty';


---Q5.WRITE A SQL QUERY TO FIND ALL TRANSACTIONS WHERE THE TOTAL_SALE IS GREATER THAN 1000.
SELECT TRANSACTIONS_ID AS TRANSACTIONS FROM RETAIL_SALES
WHERE TOTAL_SALE >= 1000 ;

---Q6.WRITE A QUERY TO FIND THE TOTAL NUMBER OF TRANSACTIONS (TRANS_ID) MADE BY EACH GENDER IN EACH CATEGORY
SELECT CATEGORY,
	   GENDER,
	   COUNT(*) AS TOTAL_TRANS
FROM RETAIL_SALES
GROUP BY CATEGORY ,GENDER
ORDER BY CATEGORY;

 ---Q7. WRITE A SQL QUERY TO CALCULATE SALE FOR EACH MONTH . FIND OUT BEST SELLING IN EACH YEAR
SELECT * 
FROM (
    SELECT 
        EXTRACT(YEAR FROM sale_date) AS year,
        EXTRACT(MONTH FROM sale_date) AS month,
        AVG(total_sale) AS avg_sale,
        RANK() OVER (
            PARTITION BY EXTRACT(YEAR FROM sale_date) 
            ORDER BY AVG(total_sale) DESC
        ) AS rank
    FROM retail_sales
    GROUP BY 1, 2
) AS t1
WHERE rank = 1
ORDER BY 1, 3 DESC;


---Q.8 WRITE A SQL QUERY TO FIND TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL SALES

SELECT CUSTOMER_ID,
	   SUM(TOTAL_SALE) AS TOTAL_SALE
FROM Retail_sales
GROUP BY CUSTOMER_ID
ORDER BY 2 DESC
LIMIT 5;

---Q9.WRITE  A SQL QUERY TO FIND THE NUMBER OF UNIQUE CUSTOMERS WHO PURCHASED ITEMS FROM EACH CATRGORY.
SELECT CATEGORY,
	  COUNT(DISTINCT(customer_id))
FROM Retail_sales
GROUP BY CATEGORY
ORDER BY 2 ASC
LIMIT 5;


----Q10.WRITE A QUERY TO CREATE EACH SHIFT AND NUMBER OF ORDERS (EXAMPLE: MORNING<=12,AFTERNON BETWEEN 12 & 17 ,EVENING > 17)

WITH hourly_sale AS (
    SELECT *,
        CASE
            WHEN EXTRACT(HOUR FROM sale_time) < 12 THEN 'Morning'
            WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
            ELSE 'Evening'
        END AS shift
    FROM retail_sales
)
---END OF PROJECT-----
SELECT
    shift,
    COUNT(*) AS total_orders
FROM hourly_sale
GROUP BY shift;

-- Check current hour
SELECT EXTRACT(HOUR FROM CURRENT_TIME);